### ISSUE TITLE
auth().signInWithPopup failing for Facebook on Firefox

### ISSUE THREAD

**Issue by theprojectsomething** [firebase/firebase-js-sdk#1003]
* Operating System version: macOS 10.13.5
  * Browser version: Firefox 61.0.01
  * Firebase SDK version: 5.2.0
  * Firebase Product: auth

### Describe the problem
Firefox's Facebook container seems to be causing the `auth().signInWithPopup` flow to fail at the redirect and close stage.

The popup window logs the warning _"Scripts may not close windows that were not opened by script."_
The SDK returns _"The popup has been closed by the user before finalizing the operation."_

Realise this is due to an addon, but it seems like it might be a fairly common issue amongst Firefox users given its popularity. It's definitely causing me heartache. I'd file a bug with Mozilla but I'm not sure of the exact details, i.e. is this likely to effect most oauth implementations?

#### Steps to reproduce:

- use Firefox with the [Facebook Container addon](https://addons.mozilla.org/en-US/firefox/addon/facebook-container/) enabled
-  attempt the `signInWithPopup` auth flow, using Facebook as the auth provider

#### Relevant Code:

```javascript
const provider = new firebase.auth.FacebookAuthProvider();
firebase.auth().signInWithPopup(provider).then(e => console.log)
.catch(e => console.log);
```

**Comment by HectorBlisS** [comment]
Same here U_U

**Comment by sadalsuud** [comment]
I have the same problem ... :c

**Comment by paolodesa** [comment]
Same problem also for me.

**Comment by Amaimersion** [comment]
Same for me.

**Comment by tzah4748** [comment]
Same problem here!...
This seems like a common bug, thanks to your help now at least we know what to tell the users when this error shows up and how to deal with it

On the bright side we can always disable the add-on
On the not so bright side (For Mozilla) some people will just change browser...

**Comment by alkymst** [comment]
I'm also seeing this for Github withPopup as well. withRedirect it fails with no errors. However this is only happening for one user. We can not seem to figure out why.



``` jsx
  const authenticate = provider => {
    console.log('Logging In');
    const authProvider = new firebase.auth[`${provider}AuthProvider`]();
    firebase
      .auth()
      .signInWithPopup(authProvider)
      .catch(err => {
        console.log(err);
      });
  };

```

```sh
{
code: "auth/popup-closed-by-user"
message: "The popup has been closed by the user before finalizing the operation."
}
```

Any insight would be helpful.

**Comment by rootux** [comment]
Still happening

**Comment by rootux** [comment]
And Still happening

**Comment by rommelpe** [comment]
@rootux I was able to [test](https://onlinereservation-2lx.firebaseapp.com/facebook-popup.html) signInWithPopup in Firefox v60.0 (with default browser settings) without having any issues. There must be some issues with the browser used. It could be set to block popups.

**Comment by theprojectsomething** [comment]
@rommelpe the original issue is specifically referring to Firefox version 61 with Facebook container. I've checked your test case and the problem persists in Firefox 70 / 71.

**Comment by rootux** [comment]
Exactly. As @theprojectsomething suggested.
@rommelpe try to open a firebase app from within Facebook using their Facebook container and you'll be able to reproduce.

**Comment by rommelpe** [comment]
@theprojectsomething @rootux ops missed that, my bad. After adding Facebook container, I ran into the same issue. 

It seems that it is working as expected as the [plugin](https://github.com/mozilla/contain-facebook#logging-in-or-creating-accounts-on-other-websites-using-facebook) itself says:

> Websites that allow you to create an account or log in using Facebook will generally not work properly.

It would be helpful if you could reach out to [them](https://github.com/mozilla/contain-facebook/issues). They may be able to provide some points to resolve the issue.

**Comment by theprojectsomething** [comment]
@rommelpe thanks, yes the plugin is definitely working as expected - it's fbauth that's not.

Currently fbauth simply fails silently (albeit with a popup error). Given the proliferation of blockers and contextual containers I guess a basic suggestion would be to return a clearer error that doesn't require a lot of research.

Building up from that, a message in the oauth window explaining that it is unable to communicate with it's parent, along with some instructions to the user on how to resolve things (perhaps providing a link to be pasted into the original context?) would be a great outcome.

**Comment by rootux** [comment]
@rommelpe Thank you.
This is pretty serious in my opinion.
That above means that `Firebase apps` won't allow `authentication` from within `Facebook containers`.

As @theprojectsomething suggested, a message in the `oauth` window with instructions would be a better practice here then failing silently.
Thank you.

**Comment by rommelpe** [comment]
Thanks for all the inputs. While this is currently an expected limitation, we'll treat this as a feature request and keep this open.

**Comment by filipsuk** [comment]
Any updates on this or possible workarounds please? Our firebase app is not usable when shared over facebook (mobile user opens it in facebook container).

**Comment by damechen** [comment]
Any update? My user is hitting the same issue.

**Comment by tzah4748** [comment]
This seems like an issue with FF or the Extension itself, and i don't think either will try to fix this.
Tell your user(s) to disable the Facebook container extension.

**Comment by rootux** [comment]
It's beyond the extension and happens to many users that does not have that
extension installed

**Comment by looptheloop88** [comment]
Hi All, this behavior is still reproducible using the latest version (8.6.1) of the SDK. If your Mozilla Firefox browser has [Facebook Container](https://addons.mozilla.org/en-US/firefox/addon/facebook-container/) addon or extension enabled, Firebase Facebook Authentication will fail.

I've filed a bug for internal tracking. We can't provide timelines or details, so keep an eye out on our release notes or this issue thread to get updates in the future.

**Comment by weixifan** [comment]
For reference the internal bug is b/188185399.

**Comment by eidan66** [comment]
Hey!
Using Firefox version:`89.0 (64-bit)`, I get the same errors for facebook&google login.
the errors:
1- 
`Opening multiple popups was blocked due to lack of user activation.`
2- 
`The popup has been closed by the user before finalizing the operation`

Any help will be good.

**Comment by theprojectsomething** [comment]
@eidan66 that looks like the popups have been blocked, it's not caused by the Facebook container.

If you click the page settings icon, directly to the left of the url, you'll be presented with a permissions overlay where you can allow popups. Alternatively, follow [these official instructions](https://support.mozilla.org/en-US/kb/pop-blocker-settings-exceptions-troubleshooting) to resolve (note that the UI presented in the docs is old)

**Comment by verma1019** [comment]
I have fixed this issue. The problem is that I was triggering the popup on click of a button but I was not adding the type="button" attribute in my <button> tag. 

So what I did is following, I added type="button" and voilaaaaa, It fixed my problem.

<button type='button' onClick={SignInWithGoogle}>
         Sign In With Google
</button>

**Comment by olso** [comment]
@verma1019 this doesn't work for me, we had this since the beginning

**Comment by MdYeasinSamadArnob** [comment]
> @verma1019 this doesn't work for me, we had this since the beginning

Have you been able to solved it?

**Comment by arLevi** [comment]
@verma1019 if `type="button"` fixed your issue you probably had the button inside a `<form>` and w/o the `type` it will behave as a `submit` therefor you tried to do two things at once. adding `type="button"` fixed it because now you're not submitting the form maybe ?! ...
anyway, i had it before, this didn't solve me, but thanks for sharing !

**Comment by smac89** [comment]
I solved this issue for myself today (for firefox mobile).

The problem seems to stem from the way firefox detects malicious popups: **If the popup was not opened directly as a result of some user action, then the popup is temporarily blocked until the user allows it through.**

![firebase error-small](https://user-images.githubusercontent.com/8305511/159978115-29c2ce2f-611b-4bfc-943c-3690dc29dae0.png)

In my case, I was generating a recaptcha code before opening the popup, and this was apparently what was causing the popup to be initially blocked. After I changed the code to open the popup first, then do the recaptcha stuff, I was no longer getting any dialogs to allow popups/signinwithpopup was now successfully running.
