### ISSUE TITLE
undefined is not an object (evaluating ‘s.values’)

### ISSUE THREAD

**Issue by bhups1106** [firebase/firebase-js-sdk#2015]
* Operating System version: macOS(10.14.5)
  * Browser version: react-native
  * Firebase SDK version: 6.3.0
  * Firebase Product: all (auth, database, storage, etc)

Not able to initialize the app getting error **undefined is not an object (evaluating 's.values')**

Install the latest version of FirebaseJS SDK
Initializing it with 
{
    "apiKey": "***********",
    "authDomain": "**************",
    "databaseURL": "***************",
    "projectId": "***************",
    "storageBucket": "***************",
    "messagingSenderId": "***************",
    "appId": "***************"
}
Then on intializing. Firebase is throwing this error

**firebase.initializeApp(fbConfig)**

```javascript
{
    "apiKey": "***********",
    "authDomain": "**************",
    "databaseURL": "***************",
    "projectId": "***************",
    "storageBucket": "***************",
    "messagingSenderId": "***************",
    "appId": "***************"
}

**firebase.initializeApp(fbConfig)**

```
![Screenshot_20190723-122836_redBus (1)](https://user-images.githubusercontent.com/21304015/61690727-9e33f800-ad47-11e9-87f9-231b09f55a5b.jpg)

**Comment by Feiyang1** [comment]
I'm afraid there is not enough information for us to debug here.
Was it working for you before, or it stopped working after you upgraded to the latest version? 
Is the error really thrown from firebase? If you remove firebase from the project, does the error persist?

**Comment by andrewmcwatters** [comment]
Hi @Feiyang1, we're having this issue at [DoubleDutch](https://github.com/doubledutch) as well. While @bhups1106's information might not have been enough to debug, we can confirm this isn't an isolated case, and was recent.

My initial thoughts were that since we haven't updated any dependencies recently, and rebuilds were suddenly breaking, that perhaps somewhere in the dependency chain something had changed, or suddenly the Firebase API had changed its response body with a relevant endpoint. For us, we started seeing transient auth-related errors.

**Comment by bhups1106** [comment]
@Feiyang1 It was working fine with the previous build but when we upgraded to this version the error started. And yes the error is thrown by firebase only. If we remove firebase then rest of the code is working fine

**Comment by edwardstamps** [comment]
@Feiyang1 Building off the previous comments, from my testing this is android specific and does not occur with 6.2 so it is something that was introduced recently.

**Comment by Feiyang1** [comment]
Thanks for confirming the issue. I'm able to initialize an app and get data from RTDB with 6.3.0.

Would you be able to narrow down where the error is coming from?
Is the error thrown when calling `initializeApp()`, or is it thrown when calling a specific method on a specific product? `initializeApp()` does very little, so I'm not sure what could go wrong there. It does initialize auth, so maybe it is thrown from auth.

Can you please try stripping firebase products away one by one and see which product is causing the issue? If it is not possible, would you be able to create a minimal repro and upload it to a github repo or somewhere?

Other information that could be useful:
What version of react native are you using? Are you using the [new react-native engine](https://facebook.github.io/react-native/blog/2019/07/17/hermes)?

**Comment by edwardstamps** [comment]
@Feiyang1 This is occurring on our apps still using react 0.46 and not those using a more recent version. Also it seems to be crashing when the first firebase listener is called. I am getting the same message in the console that the original poster mentioned and what lead me to this ticket. Wish I had more to provide to go on.

**Comment by bhups1106** [comment]
We are using React-Native's 0.57.8 version. It was working fine before once we updated firebase it starts breaking. It's breaking on app initialization.
Is it somehow related to firebase performance, though we are not using it?

**Comment by edwardstamps** [comment]
@Feiyang1 I was able to find some more info from one of our apps and its occurring when evaluating "n.firebase.auth" if that helps

**Comment by hsubox76** [comment]
@bhups1106 Performance is a possibility.  It did have a bug recently on startup which has been fixed.  But are you using the all-in-one firebase import (`import firebase from 'firebase'`) vs importing packages modularly such as:
```
import firebase from 'firebase/app';
import 'firebase/auth';
import 'firebase/database';
...
```

If you're importing packages separately, and are not importing performance, performance would not cause a bug.  If you're importing the all-in-one firebase package (top), it might.  In that case, try upgrading again to the latest firebase (anything 6.3.3 or higher) or trying importing packages individually (which we generally recommend anyway, for optimizing bundle size).  You can also just try 6.3.3 either way, there have been some bug fixes.

If you are already importing packages individually (importing `firebase/app`, not `firebase`) and are not importing performance explicitly, it's probably something else.  Let us know in that case.

**Comment by Miguel-Alberto** [comment]
Similarly, seeing **Object doesn't support property or method 'values'** from the console of our internet explorer users.

Somewhere between 6.0.4 and 6.3.2 a call(s) to [.values()](https://caniuse.com/#search=.values) was/were introduced. 

We're rolling back our version for now, but this remains an open issue.

**Comment by Miguel-Alberto** [comment]
This was broken by #1811

**Comment by edwardstamps** [comment]
@Miguel-Alberto Thanks for finding the PR where this broke! We are still experiencing the issue and I've been using fixed 6.2.0 for the time being so it occurring on 6.2.4 makes sense

**Comment by Miguel-Alberto** [comment]
@edwardstamps 🍻 

Looks like you might be safe with 6.2.4, but that's as high as you can go. I see the breaking change starting with the tag _firebase6.3.0_

**Comment by bhups1106** [comment]
When and on which release can we expect the changes?

**Comment by Feiyang1** [comment]
@Miguel-Alberto You need to add polyfills to support IE11.

After `firebase@6.0.0`, we stopped shipping polyfills by default because it adds bloat to applications that don't need to support legacy browsers and we think developers knows better than us what polyfills need to be included in their app. 

We don't consider using new ES features as breaking changes anymore,
please see [Environment Support](https://firebase.google.com/support/guides/environments_js-sdk) for ways you can add polyfills.  

@bhups1106 I don't think your issue is the polyfill as `react-native` states it supports `object.values` - https://facebook.github.io/react-native/docs/javascript-environment

Can you please answer the questions @hsubox76 asked you? It will help us find the root cause for you.

**Comment by edwardstamps** [comment]
@Feiyang1 This is still an active issue for my team. Please let me know what additional information your team needs, if we should open another ticket etc

**Comment by Feiyang1** [comment]
@edwardstamps Can you please open a new issue with error log, react-native version, Firebase version, etc. 
What's most helpful is if you can create a repro and upload it to github (or somewhere else). It's hard to get all the details of your project just by words.
