### ISSUE TITLE
BUG; Auth raise error (A network error...) on iOS WKwebview

### ISSUE THREAD

**Issue by mohshraim** [firebase/firebase-js-sdk#582]
### [REQUIRED] Describe your environment

  * Operating System version:  iOS 11.2 WKWebview
  * Firebase SDK version:  4.12
  * Firebase Product: auth

### [REQUIRED] Describe the problem

loginwithemailand password fail with error ->  A network error (such as timeout, interrupted connection or unreachable host) has occurred.

#### Steps to reproduce:

just embed a html page on iOS WKWebview with a login button

#### Relevant Code:

Please help with any suggestion or work around...

**Comment by mohshraim** [comment]
@bojeil-google 
i have a confirmation from firebase support the exist of this bug on WKWebview...

the `navigator.onLine` return true but login fail with mentioned error. 
and on the other hand, firestore run successfully with all functionality on the same environment. and never return error related to connection..

Any help, work around.. ?

**Comment by bojeil-google** [comment]
Again, I cannot debug this. I have no idea what firestore uses. We don't share the same mechanism for processing http requests.
There is no bug with WKWebview (you probably misunderstood or miscommunicated the issue with support), otherwise we would hear a lot of issues with WKWebView in general.
There are currently 2 issues close to yours:
1. `navigator.onLine` incorrectly returning false
2. bug with ionic latest version which uses WKWebView instead of UIWebView which cause OAuth sign in to fail (only that flow).

None of these match your report.

**Comment by bojeil-google** [comment]
To clarify the ionic iOS issue is not specific to WKWebView. It is due to them using a locally hosted server (http://localhost) to serve the files instead of (file://) as they used to.

**Comment by mohshraim** [comment]
@bojeil-google
this shared minimal test case
https://drive.google.com/drive/folders/10zv-OaHduIuP2q347TCIVxKe8kCbAj0z?usp=sharing
please have look 
you need just to set the config of firebase project at line 38 from file firebaseTest.js

firebase support confirm the replicate of my case exactly...

i am on this case from 1 month iam very happy that someone reply that quickly...

**Comment by bojeil-google** [comment]
In general you should go through support for similar requests. GitHub is not really the channel for similar support questions. I will see if I have time to look into this in the coming weeks. Thanks.

**Comment by mohshraim** [comment]
@bojeil-google
i am not using ionic.. i just load html with firebase auth and firestore javascript on WKWebview.. 

    NSString *urlAddress = [[NSBundle mainBundle] pathForResource:@"folder/index" ofType:@"html"];

    NSURL *url = [NSURL fileURLWithPath:urlAddress];
    NSString * basePath = [urlAddress substringToIndex:[urlAddress length] - 11]; //   (/index.html) length 11
    NSURL *baseurl = [NSURL fileURLWithPath:basePath];
    [self.webView loadFileURL:url allowingReadAccessToURL:  baseurl];

i hope that you look at that case
Thanks for your time

**Comment by mohshraim** [comment]
@bojeil-google 
Hello,
I found the source of the error...

we are using allowFileAccessFromFileURLs on WKWebview, this to enable access to local files in WKWebview environment... if we comment this firebase login will work from SDK normally; but this will stop the application from working and read the other files on xCode project..

**Note that navigatore.onLine() is always true on both cases.**

`[self.webView.configuration.preferences setValue:@TRUE forKey:@"allowFileAccessFromFileURLs"];`

Any guide from this point?
Thanks

**Comment by mk0116** [comment]
I got the same issue.
This is the stacktrace.
We have about 1,500 error per day.
Please investigate about this issue asap.

Pi A network error (such as timeout, interrupted connection or unreachable host) has occurred. 
    node_modules/@firebase/auth/dist/auth.js:19:302 
    node_modules/@firebase/auth/dist/auth.js:142:273 
    node_modules/@firebase/auth/dist/auth.js:139:284 
    node_modules/@firebase/auth/dist/auth.js:45:482 qd
    node_modules/@firebase/auth/dist/auth.js:44:296 G
    node_modules/@firebase/auth/dist/auth.js:74:449 cf
    node_modules/@firebase/auth/dist/auth.js:77:229 ef
    node_modules/@firebase/auth/dist/auth.js:75:360 jc
    node_modules/@firebase/auth/dist/auth.js:75:334 Ab
    [native code] 
    node_modules/event-target-shim/lib/event-target.js:172:43 prototype
    node_modules/react-native/Libraries/Network/XMLHttpRequest.js:174:11 value
    node_modules/react-native/Libraries/Network/XMLHttpRequest.js:414:54 value
    node_modules/react-native/Libraries/Network/XMLHttpRequest.js:517:45 
    node_modules/react-native/Libraries/EventEmitter/EventEmitter.js:187:34 value
    node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:252:9 value
    node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:108:92 
    node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:222:24 value
    node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:105:16 value
    [native code]

**Comment by bojeil-google** [comment]
We finally got the cURL command for this. It turns out there is some issue when the preflight OPTIONS request contains an origin with a file:// URL. It's weird that it is manifesting here and now. This is not a client SDK issue. We have filed the bug with the Auth team's backend engineers. You can follow up with the support team on that.

**Comment by mohshraim** [comment]
Hello @bojeil-google 

Yes they ask me for curl couple days ago and i sent it yesterday...

This Fiall and only when i set `[self.webView.configuration.preferences setValue:@true forKey:@"allowFileAccessFromFileURLs"];`

```
curl 'https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyPassword?key=aaaaaaa' \
-XOPTIONS \
-H 'Access-Control-Request-Headers: cache-control,content-type' \
-H 'User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 11_2 like Mac OS X) AppleWebKit/604.4.7 (KHTML, like Gecko) Mobile/15C107' \
-H 'Origin: file://' \
-H 'Access-Control-Request-Method: POST'
```


and this the normal one that pass on WKWebview when i remove `[self.webView.configuration.preferences setValue:@true forKey:@"allowFileAccessFromFileURLs"];`

```
curl 'https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyPassword?key=aaaaaa' \
-XOPTIONS \
-H 'Access-Control-Request-Headers: cache-control,content-type' \
-H 'User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 11_2 like Mac OS X) AppleWebKit/604.4.7 (KHTML, like Gecko) Mobile/15C107' \
-H 'Origin: null' \
-H 'Access-Control-Request-Method: POST'
```

Thanks for follow up...

**Comment by tgensol** [comment]
Any news on this one ? I think I also have the issue (iOS, Ionic)

**Comment by mohshraim** [comment]
last reply from support 2 weeks ago

`I have checked on our end and there is still a discussion regarding this. Please take note that we cannot disclose details about timelines for the bugfix. You may just watch out the bugfix in our release notes and our blog. I hope for your understanding.
`

this case opened at 27th feb; after 50 emails they confirm the bug, but i cant have clear response from support if they will fix it.

I think Ionic will be affected if they use WKWebView;  note that only if you want to read local files from WKWebView if you change the configuration
`[self.webView.configuration.preferences setValue:@TRUE forKey:@"allowFileAccessFromFileURLs"];`

otherwise the request origin is valid..

**Comment by mohshraim** [comment]
I think problem solved...
Not sure Yet..
Just sent Firebase Support asking for a confirmation..
Anyone still face this error?

**Comment by bojeil-google** [comment]
Yeah, we apologize for the delay, the original reported CORS problem should be fixed.

**Comment by adamduren** [comment]
What version was this fixed in?

**Comment by bojeil-google** [comment]
This is a backend related change. It should apply to all versions.

**Comment by mohshraim** [comment]
Thanks @bojeil-google  for confirmation
Close issue

**Comment by adamduren** [comment]
I am still seeing auth errors logged on our Sentry instance for iOS.
