### ISSUE TITLE
@firebase/firestore: Firestore (12.3.0): FIRESTORE (12.3.0) INTERNAL ASSERTION FAILED: Unexpected state (ID: ca9) CONTEXT: {"ve":-1}

### ISSUE THREAD

**Issue by jpfbarreira** [firebase/firebase-js-sdk#9267]
### Operating System

Windows 11

### Environment (if applicable)

Node.js version: 22.19.0

### Firebase SDK Version

12.3.0

### Firebase SDK Product(s)

Firestore

### Project Tooling

- Framework: Angular (v20.2.4)
- Language: TypeScript (v5.8.3)
- Test runner: Playwright (v1.55.0)
- Firebase Emulator Suite (v13.16.0 via firebase-tools)
- Node.js (v22.19.1)

### Detailed Problem Description

We are running end-to-end tests with Playwright against our Angular app.

What we were trying to achieve:

We want to simulate user permission changes in our tests by adding and deleting a manager document in Firestore. The UI should react to these changes by redirecting the user back to a summary page.

What actually happened:

Occasionally, the tests fail due to a Firestore internal assertion crash. Instead of the expected redirect, the app crashes with the following error in the console:

@firebase/firestore: Firestore (12.3.0): FIRESTORE (12.3.0) INTERNAL ASSERTION FAILED: Unexpected state (ID: ca9) CONTEXT: {"ve":-1}

<img width="1908" height="1027" alt="Image" src="https://github.com/user-attachments/assets/47b53005-eb85-4105-a5f7-1b4a936300bc" />

This happens only intermittently (flaky). Based on test runs:

First run: 30 tests -> 26 passed, 4 failed

Second run: 30 tests -> 25 passed, 5 failed

This means roughly 15–17% of our runs fail due to this issue. When it doesn’t crash, everything works as expected.

Context:

- The error occurs only when running against the Firebase Emulator.
- It happens when Firestore documents are added and deleted quickly (add manager -> delete manager).

We believe this may be related to: https://github.com/firebase/firebase-js-sdk/issues/8250

### Steps and code to reproduce issue

We have not been able to create a minimal reproduction, as this error only appears intermittently (flaky) during our Playwright end-to-end tests against the Firestore emulator. However, the issue seems related to rapid document add/delete operations while listening to Firestore against the emulator.

The sequence that seems to trigger it is:

1. User is assigned a “manager” role -> Firestore document is added.
2. Shortly after, the manager is deleted from Firestore (document removed).
3. Our Angular app listens to Firestore snapshot changes and updates the UI.

**Comment by MarkDuckworth** [comment]
Is this an issue you have experienced before SDK version 12.3.0?

**Comment by basvandorst** [comment]
Same here, Angular 19.2.16, haven't seen this (ca9,b815) issue before on a local machine with emulators:

```
APPLICATION_ERROR_HANDLER Error: FIRESTORE (12.3.0) INTERNAL ASSERTION FAILED: Unexpected state (ID: b815) CONTEXT: {"Pc":"Error: FIRESTORE (12.3.0) INTERNAL ASSERTION FAILED: Unexpected state (ID: ca9) CONTEXT: {\"ve\":-1}
    at __PRIVATE__fail (http://localhost:4201/@fs/Users/bas/Projects/cash-register/.angular/cache/19.2.16/point-of-sale/vite/deps/@angular_fire_firestore.js?v=abbb359d:3437:32)
    at __PRIVATE_hardAssert (http://localhost:4201/@fs/Users/bas/Projects/cash-register/.angular/cache/19.2.16/point-of-sale/vite/deps/@angular_fire_firestore.js?v=abbb359d:3441:46)
    at __PRIVATE_TargetState.Ke (http://localhost:4201/@fs/Users/bas/Projects/cash-register/.angular/cache/19.2.16/point-of-sale/vite/deps/@angular_fire_firestore.js?v=abbb359d:7538:19)
    at http://localhost:4201/@fs/Users/bas/Projects/cash-register/.angular/cache/19.2.16/point-of-sale/vite/deps/@angular_fire_firestore.js?v=abbb359d:7574:13
    at Array.forEach (<anonymous>)
    at __PRIVATE_WatchChangeAggregator.forEachTarget (http://localhost:4201/@fs/Users/bas/Projects/cash-register/.angular/cache/19.2.16/point-of-sale/vite/deps/@angular_fire_firestore.js?v=abbb359d:7604:42)
    at __PRIVATE_WatchChangeAggregator.tt (http://localhost:4201/@fs/Users/bas/Projects/cash-register/.angular/cache/19.2.16/point-of-sale/vite/deps/@angular_fire_firestore.js?v=abbb359d:7567:10)
    at http://localhost:4201/@fs/Users/bas/Projects/cash-register/.angular/cache/19.2.16/point-of-sale/vite/deps/@angular_fire_firestore.js?v=abbb359d:14167:137
    at Generator.next (<anonymous>)
    at http://localhost:4201/@fs/Users/bas/Projects/cash-register/.angular/cache/19.2.16/point-of-sale/vite/deps/chunk-YZEP45GQ.js?v=abbb359d:88:61"}
    at __PRIVATE__fail (index.esm.js:199:32)
    at fail (index.esm.js:185:41)
    at __PRIVATE_AsyncQueueImpl.uc (index.esm.js:19560:16)
    at __PRIVATE_AsyncQueueImpl.enqueue (index.esm.js:19503:14)
    at __PRIVATE_AsyncQueueImpl.enqueueAndForget (index.esm.js:19488:10)
    at _DelayedOperation.handleDelayElapsed (index.esm.js:16130:21)
    at index.esm.js:16110:46
    at timer (zone.js:1752:27)
    at _ZoneDelegate.invokeTask (zone.js:364:171)
    
....

    logger.handler.ts:81 APPLICATION_ERROR_HANDLER Error: FIRESTORE (12.3.0) INTERNAL ASSERTION FAILED: Unexpected state (ID: b815) CONTEXT: {"Pc":"Error: FIRESTORE (12.3.0) INTERNAL ASSERTION FAILED: Unexpected state (ID: ca9) CONTEXT: {\"ve\":-1}
    at __PRIVATE__fail (http://localhost:4201/@fs/Users/bas/Projects/cash-register/.angular/cache/19.2.16/point-of-sale/vite/deps/@angular_fire_firestore.js?v=abbb359d:3437:32)
    at __PRIVATE_hardAssert (http://localhost:4201/@fs/Users/bas/Projects/cash-register/.angular/cache/19.2.16/point-of-sale/vite/deps/@angular_fire_firestore.js?v=abbb359d:3441:46)
    at __PRIVATE_TargetState.Ke (http://localhost:4201/@fs/Users/bas/Projects/cash-register/.angular/cache/19.2.16/point-of-sale/vite/deps/@angular_fire_firestore.js?v=abbb359d:7538:19)
    at http://localhost:4201/@fs/Users/bas/Projects/cash-register/.angular/cache/19.2.16/point-of-sale/vite/deps/@angular_fire_firestore.js?v=abbb359d:7574:13
    at Array.forEach (<anonymous>)
    at __PRIVATE_WatchChangeAggregator.forEachTarget (http://localhost:4201/@fs/Users/bas/Projects/cash-register/.angular/cache/19.2.16/point-of-sale/vite/deps/@angular_fire_firestore.js?v=abbb359d:7604:42)
    at __PRIVATE_WatchChangeAggregator.tt (http://localhost:4201/@fs/Users/bas/Projects/cash-register/.angular/cache/19.2.16/point-of-sale/vite/deps/@angular_fire_firestore.js?v=abbb359d:7567:10)
    at http://localhost:4201/@fs/Users/bas/Projects/cash-register/.angular/cache/19.2.16/point-of-sale/vite/deps/@angular_fire_firestore.js?v=abbb359d:14167:137
    at Generator.next (<anonymous>)
    at http://localhost:4201/@fs/Users/bas/Projects/cash-register/.angular/cache/19.2.16/point-of-sale/vite/deps/chunk-YZEP45GQ.js?v=abbb359d:88:61"}
```

edit, just had it 2 times:
1) fixed with page refresh
2) not fixed with page refresh, only option was to clear local storage

**Comment by jpfbarreira** [comment]
Yes, the crash happens in a previous version as well. We were on "firebase": "12.2.1", which brings in the "@firebase/firestore: Firestore (12.2.0): FIRESTORE (12.2.0) INTERNAL ASSERTION FAILED: Unexpected state (ID: ca9) CONTEXT: {"ve":-1}". We observed the same flaky behavior there.

We updated to 12.3.0, hoping the issue would be resolved, but the same assertion failure still occurs.

<img width="1911" height="1023" alt="Image" src="https://github.com/user-attachments/assets/425bfca3-609b-4684-9d3e-85690a6b018d" />

**Comment by MarkDuckworth** [comment]
@jpfbarreira, if you're still experiencing this issue during testing, can you enable debug logging for the Firestore SDK and send me the complete logs? `import {setLogLevel} from 'firebase/firestore'; setLogLevel('debug');`

**Comment by jpfbarreira** [comment]
Yes, it's still happening. 

We are now in version 12.6.0

Here is the screenshot of the error:
<img width="1274" height="790" alt="Image" src="https://github.com/user-attachments/assets/6750537a-8699-4421-9b6a-d6ae29aff504" />

These are the logs:
[localhost-1763643425700.log](https://github.com/user-attachments/files/23654373/localhost-1763643425700.log)

**Comment by MarkDuckworth** [comment]
Thanks for the updated logs @jpfbarreira. Can you confirm that this is the entire log from and none was truncated from the top?

**Comment by MarkDuckworth** [comment]
@jpfbarreira, the logs are very helpful. Are you able to share the Firestore rules for that collection?

**Comment by jpfbarreira** [comment]
Related to the first question: 
- Yes, I think so. I exported it from the browser dev tools. It should include everything from the moment the test started until the crash.

Related to the second question:
- Is it ok if I send you the rules to a private email address?

**Comment by MarkDuckworth** [comment]
Thanks for your response. I was able to create a rule and test scenario that produced a similar permission denied error, so I no longer need to see your rule.

However, I was not able to reproduce the internal assertion. So I'm wondering if you can help me get more information because you seem to have a repeatable reproduction?

Would you be willing to add [this code snippet](https://gist.github.com/MarkDuckworth/2967b22bf7e1c0d0f75c022d3fb8f922) to your source (test sources only, not for production code), re-run the test, and provide us with the updated log? This will help me see the messages going over the network and could help me determine if the underlying bug is in client-side networking components or server-side networking components. Thanks!

**Comment by jpfbarreira** [comment]
Hello @MarkDuckworth, is it possible for us to send you the output file via private email?

**Comment by MarkDuckworth** [comment]
The recommended way is to create a new ticket at https://firebase.google.com/support/troubleshooter/contact and then upload the file there. Reference this GitHub issue (https://github.com/firebase/firebase-js-sdk/issues/9267) and request the the ticket/log is forwarded to markduckworth@. Thanks!

**Comment by MorganTrudeau** [comment]
This happens to me on 12.6.0 almost every time onSnapshot connects to a collection with insufficient permissions.

**Comment by MarkDuckworth** [comment]
@MorganTrudeau 

> This happens to me on 12.6.0 almost every time onSnapshot connects to a collection with insufficient permissions.

Are you seeing the same identifier `(ID: ca9)` in your error message? And, are you seeing this against the emulator or production Firestore backend?

**Comment by MarkDuckworth** [comment]
@jpfbarreira, thanks for sending the logs. I was able to review them today. The logs show an unexpected message coming from the emulator. I'm not sure if this is specific to the emulator or shared with the Firestore backend.

Can you confirm which version of the emulator you are using?

Also, did you observe any log statements from the emulator when these issues occurred?

Thanks for your help

**Comment by jpfbarreira** [comment]
Emulator version: 1.19.8 (I think)

Related to the log statements, I don't really see anything weird when the crash occurs. I will create a new ticket and send the Firebase logs through support



And these are the screenshots from the cmd's that pop up when I run the emulator:

<img width="1110" height="621" alt="Image" src="https://github.com/user-attachments/assets/49644737-e3e2-4a68-9cfa-b90cef48f5a4" />

<img width="1114" height="627" alt="Image" src="https://github.com/user-attachments/assets/9c5761b7-5732-4808-a41c-c7cb670b6600" />

These include all emulator output up to the point where the test fails. If you need the logs from the beginning as plain text instead of screenshots, I can provide those as well

**Comment by thomaskleiven** [comment]
I also see this issue in `v12.6.0`, as @MorganTrudeau mentioned, it seems to happen almost every time `onSnapshot` subscribes to a collection with insufficient permissions. Do you have any advice on how to mitigate this error? 

Thanks in advance.

**Comment by MarkDuckworth** [comment]
Thanks for the additional feedback @thomaskleiven. Are you seeing this in production, with the emulator, or both?

**Comment by thomaskleiven** [comment]
Production. Haven't reproduced it in the emulator so far.

**Comment by MarkDuckworth** [comment]
Thanks for clarifying, it's helpful for me to understand this is not specific to the emulator.

@thomaskleiven or @jpfbarreira, are either of you able to create a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that you can share with me?

I've attempted to reproduce by setting up a snapshot listener with insufficient permissions. But I've been unsuccessful against prod and the emulator. I'm wondering if there's something specific in your queries that I'm not considering in my attempts.

**Comment by thomaskleiven** [comment]
I'll try to come up with a reproducible example. Will let you know once I have more details.

**Comment by thomaskleiven** [comment]
Ok this is what we've got so far to reproduce the error: 

Environment:

- Next.js 16.0.7
- React 19.2.1
- Firebase JS SDK 12.6.0
- reactStrictMode: true

```ts
function TabA() {
  useEffect(() => {
    const unsub1 = onSnapshot(
      collection(db, 'allowed-path'),
      (snap) => console.log('ok', snap.size),
      (err) => console.error(err)
    )
    const unsub2 = onSnapshot(
      collection(db, 'denied-path'),
      (snap) => console.log('ok', snap.size),
      (err) => console.error(err)
    )
    return () => { unsub1(); unsub2() }
  }, [])

  return <div>Tab A</div>
}
```

**Steps:**
1. Load page (Tab A mounts, listener 2 gets permission denied)
2. Switch to Tab B
3. Immediately switch back to Tab A
4. Error appears in console

**Error:**
```
FIRESTORE (12.6.0) INTERNAL ASSERTION FAILED: Unexpected state (ID: ca9) CONTEXT: {"ve":-1}
```

Only reproducible with `reactStrictMode: true`.


Let me know if this helps. If not we can try to dive a bit deeper into what's actually happening. 

Thanks a lot for your help.

**Comment by MarkDuckworth** [comment]
@thomaskleiven, thanks for the code snippet. I was able to reproduce with intermittent frequency. There appears to be a race condition in the internal target management, between the SDK and server. This is different root cause than the cause that was fixed in 12.3.0. I've engaged with others on my team to help look into this, but I don't currently have a timeline for a fix, as we're balancing server high priority projects.

**Comment by kulakowka** [comment]
May I ask if there are any updates on this issue? This is a super critical bug. All my iOS users are complaining about it.

**Comment by kopax** [comment]
Hello, we also have a lot of issue with massive user base, it's quite critical, can you please give some info ?

**Comment by opack** [comment]
I too start seeing this issue with Firestore 12.9.0:
```
FIRESTORE (12.9.0) INTERNAL ASSERTION FAILED: Unexpected state (ID: ca9) CONTEXT: {"ve":-1}
```
but also with `b815`:
```
IRESTORE (12.9.0) INTERNAL ASSERTION FAILED: Unexpected state (ID: b815) CONTEXT: {"Pc":"FIRESTORE (12.9.0) INTERNAL ASSERTION FAILED: Unexpected state (ID: ca9) CONTEXT: {\"ve\":-1}
```
Before the errors I tend to have this warning:
```
@firebase/firestore: Firestore (12.9.0): WebChannelConnection RPC 'Listen' stream 0x76533753 transport errored. Name: undefined Message: undefined
```

I initially filed an issue for the b815 in #9794 and now I see that this ca9 is also reported more recently in #9491 . It all seems related, so I don't know where to post my new related reports anymore 😅 

Anyway, it happens on production only for me, and I cannot reproduce it easily, and I don't know if my users are seeing some kind of error or if it's silent. And for information I'm using Vue (with Quasar and Capacitor) so I think the label "stack:Vue" could also be added to this issue.

**Comment by opack** [comment]
FWIW, still seeing this issue using 12.12:
```
FIRESTORE (12.12.0) INTERNAL ASSERTION FAILED: Unexpected state (ID: b815) CONTEXT: {"Pc":"Error: FIRESTORE (12.12.0) INTERNAL ASSERTION FAILED: Unexpected state (ID: ca9) CONTEXT: {\"ve\":-1}
```
(seen today)

If I look at the logs in the Sentry issue, I see this a bit earlier:
```
POST: https://firestore.googleapis.com/google.firestore.v1.Firestore/Listen/channel?VER=8&database=projects%2F<REDACTED>%2Fdatabases%2F(default)&gsessionid=<REDACTED>&SID=<REDACTED>&RID=<REDACTED>&AID=<REDACTED>&t=1 [200]
```
Hope it helps resolving this really annoying issue 🤞

**Comment by agardnerIT** [comment]
Hit this too:

```
[BROWSER] error: [2026-04-30T08:28:18.449Z]  @firebase/firestore: Firestore (12.12.0): FIRESTORE (12.12.0) INTERNAL ASSERTION FAILED: Unexpected state (ID: ca9) CONTEXT: {"ve":-1}
[BROWSER] error: [2026-04-30T08:28:18.449Z]  @firebase/firestore: Firestore (12.12.0): INTERNAL UNHANDLED ERROR:  Error: FIRESTORE (12.12.0) INTERNAL ASSERTION FAILED: Unexpected state (ID: ca9) CONTEXT: {"ve":-1}
    at __PRIVATE__fail (http://localhost:5175/node_modules/.vite/deps/firebase_firestore.js?v=cc90ffd9:2593:32)
    at __PRIVATE_hardAssert (http://localhost:5175/node_modules/.vite/deps/firebase_firestore.js?v=cc90ffd9:2597:46)
    at __PRIVATE_TargetState.We (http://localhost:5175/node_modules/.vite/deps/firebase_firestore.js?v=cc90ffd9:6713:19)
    at http://localhost:5175/node_modules/.vite/deps/firebase_firestore.js?v=cc90ffd9:6749:13
    at Array.forEach (<anonymous>)
    at __PRIVATE_WatchChangeAggregator.forEachTarget (http://localhost:5175/node_modules/.vite/deps/firebase_firestore.js?v=cc90ffd9:6779:42)
    at __PRIVATE_WatchChangeAggregator.tt (http://localhost:5175/node_modules/.vite/deps/firebase_firestore.js?v=cc90ffd9:6742:10)
    at __PRIVATE_onWatchStreamChange (http://localhost:5175/node_modules/.vite/deps/firebase_firestore.js?v=cc90ffd9:13316:135)
    at __PRIVATE_PersistentListenStream.onNext (http://localhost:5175/node_modules/.vite/deps/firebase_firestore.js?v=cc90ffd9:12967:26)
    at http://localhost:5175/node_modules/.vite/deps/firebase_firestore.js?v=cc90ffd9:12926:52
```

**Comment by MarkDuckworth** [comment]
We've submitted https://github.com/firebase/firebase-js-sdk/pull/9842, which addresses the root cause of this issue as identified using @thomaskleiven's snippet from https://github.com/firebase/firebase-js-sdk/issues/9267#issuecomment-3633931837.  The SDK with this fix will be released in the next few weeks.

I'll close this for now, but please leave a comment or open a new issue if you see this error in the future. There have been multiple causes of the `ca9` assertion so far. I'm hoping this fix helps all of you continuing to report the assertion.

**Comment by ShaneBreazeale** [comment]
having this issue too. will try downgrading. 

```
(Found the exact root cause. Line 6582 of the SDK:

  $e() { this.ve += 1; }              // recordPendingTargetRequest: increment
  We() { this.ve -= 1;                 // recordTargetResponse: decrement
    __PRIVATE_hardAssert(this.ve >= 0, 3241, { ve: this.ve }); }

  ve = outstandingResponses counter in WatchChangeAggregator's per-target TargetState. The assertion fires when recordTargetResponse() is called more times 
  than recordPendingTargetRequest() — the SDK received a watch target-change response with no matching outstanding request → counter goes to -1 → hard-assert →
   kills the entire AsyncQueue → every later op throws b815.
  
  This is a genuine SDK defect: bookkeeping desync from stale/duplicate watch target responses (your original commit comment — "stale HTTP/2 WebChannel
  responses from previous sessions" — was actually on the right track). Let me see what calls We() and check for known SDK fixes:

⏺ Let me find what calls We() and check for known SDK issues in parallel:
     3 matches in 1F:
     … +67 lines (ctrl+o to expand)

⏺ Web Search("firebase-js-sdk INTERNAL ASSERTION FAILED Unexpected state ca9 outstandingResponses recordTargetResponse 2026")
  ⎿  Did 1 search in 7s

⏺ This is already a known, open SDK bug: firebase-js-sdk #9267 (https://github.com/firebase/firebase-js-sdk/issues/9267) — exact same ca9 / {"ve":-1}, reported
   on 12.3.0, still unfixed in 12.13.0.)
```

**Comment by kopax** [comment]
Any update @MarkDuckworth ?

**Comment by ShaneBreazeale** [comment]
We hit this on `firebase@12.13.0` (React 19 + Vite SPA, `memoryLocalCache`, `experimentalAutoDetectLongPolling`) and traced it to a deterministic, minimal trigger. Sharing in case it helps — and to answer @MarkDuckworth's "before 12.3.0?": for us it reproduces on **12.2.0 through 12.13.0**, so it isn't specific to 12.3.0.

### Minimal trigger

The **first** Firestore operation after page load is a single server `getDoc()` on a freshly-opened WebChannel:

```js
const db = initializeFirestore(app, { localCache: memoryLocalCache() });
// first op on the cold stream:
await getDoc(doc(db, 'users', uid));   // transient listen: addTarget -> CURRENT -> removeTarget
```

`ca9` fires **~60ms after that `getDoc` resolves** — i.e. during the target **teardown**, not the add. Stack is always the watch path:

```
__PRIVATE_TargetState.recordTargetResponse  (hardAssert(this.outstandingResponses >= 0, 0xca9))
__PRIVATE_WatchChangeAggregator.handleTargetChange
... forEachTarget -> onWatchStreamChange
```

i.e. `TargetState.outstandingResponses` goes to `-1`: a watch `Removed`/`Added` target-change is processed with no matching `recordPendingTargetRequest()`.

### Why it's so damaging

The `0xca9` throw propagates into the `AsyncQueue`, which then permanently fails (`verifyNotFailed` → `fail(0xb815)`). So one stray target-ack doesn't just drop a read — it **bricks the entire Firestore client for the page lifetime**: every subsequent `getDoc`/`getDocs`/`onSnapshot`/write throws `b815`. That cascade (one `ca9` → dozens of `b815`) is the most damaging part.

### Workaround that fixed it for us

Replacing that first transient `getDoc` with a **persistent `onSnapshot`** (resolve the first server snapshot, keep the listener open) eliminated `ca9` entirely across many loads. A long-lived target never tears down, so there's no remove-phase race. It also seems to "anchor" the WebChannel so the subsequent burst of reads is fine.

So the practical guidance is: **avoid a transient `getDoc()` as the very first op on a cold WebChannel** — use a kept-open listener instead.

### Suggested SDK fix

Treat an unexpected extra target response as a recoverable inconsistency (drop/re-listen the affected target) instead of a `hardAssert` that kills the `AsyncQueue`. Turning one stray frame into a total, unrecoverable client outage is what makes this so severe in production.

Repro conditions: `memoryLocalCache`, a server `getDoc` as the first op on a just-initialized client, intermittent in general but deterministic in our app at cold start.
